"""empty message

Revision ID: 07198f78c30d
Revises: a08049920a6c
Create Date: 2021-03-26 22:52:25.415745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07198f78c30d'
down_revision = 'a08049920a6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
